<!doctype html>
<html class="site background">

<head>
  <meta charset="utf-8" />
  <title>故事 | Stori</title>
  <meta name="keywords" content="Stori, 小故事" />
  <meta name="description" content="一个讲故事的小网站。" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/animate.css/3.5.0/animate.min.css" />
<!--  <link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" />-->
  <link rel="stylesheet" type="text/css" href="css/v2.css" />
<!--  <link rel="stylesheet" type="text/css" href="css/header" />-->
  <script type="application/javascript" src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
  <script type="application/javascript" src="js/home.js"></script>
  <script src="//cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
  <nav class="global navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">展开导航栏</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">故事 | Stori</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <a href="/">
              <i class="glyphicon glyphicon-home"></i>
              首页
            </a>
          </li>
          <li>
            <a href="/memory">
              <i class="glyphicon glyphicon-film"></i>
              回忆
            </a>
          </li>
          <li>
            <a href="http://www.douban.com/people/yfwz100/doulists/all">
              <i class="glyphicon glyphicon-tag"></i>
              收藏
            </a>
          </li>
          <li class="active">
            <a href="/contact">
              <i class="glyphicon glyphicon-comment"></i>
              联系
              <span class="sr-only">(当前页)</span>
            </a>
          </li>
          <li>
            <a href="/about">
              <i class="glyphicon glyphicon-user"></i>
              关于
            </a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="http://weibo.com/yfwz100">@yfwz100</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="about pagebox container animated fadeIn">
    <div class="page-header">
      <h3>联系、留言 | Contact</h3>
    </div>
    <form action="draft.php" class="form container-fluid">
      <div class="form-group">
        <label for="tell-title">故事名称：</label>
        <input type="text" class="form-control" name="title" id="tell-title" placeholder="无题？" />
      </div>
      <div class="form-group">
        <label for="tell-author">您的大名：</label>
        <input type="text" class="form-control" name="author" id="tell-name" placeholder="昵称之类" />
      </div>
      <div class="form-group">
        <label for="tell-content">您的故事：</label>
        <textarea id="tell-content" class="form-control" name="content" rows="8" placeholder="真实故事、道听途说都可以"></textarea>
      </div>
      <div class="form-actions">
        <button type="submit" class="btn btn-primary">提交</button>
        <button type="reset" class="btn btn-default">重置</button>
      </div>
      <br />
      <hr />
      <p>历史提交：</p>
      <ul class="drafts-list">
        <li>暂时还没有~</li>
      </ul>
    </form>
  </div>

  <div class="footer">&copy; yfwz100</div>
</body>

</html>
