<!doctype html>
<html class="site background">

<head>
  <meta charset="utf-8" />
  <title>故事 | Stori</title>
  <meta name="keywords" content="Stori, 小故事" />
  <meta name="description" content="一个讲故事的小网站。" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/animate.css/3.5.0/animate.min.css" />
<!--  <link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" />-->
  <link rel="stylesheet" type="text/css" href="css/v2.css" />
<!--  <link rel="stylesheet" type="text/css" href="css/header" />-->
  <script type="application/javascript" src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
<!--  <script type="application/javascript" src="js/home.js"></script>-->
  <script src="//cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
  <nav class="global navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">展开导航栏</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">故事 | Stori</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="#">
              <i class="glyphicon glyphicon-home"></i>
              首页
              <span class="sr-only">(当前页)</span>
            </a>
          </li>
          <li>
            <a href="/memory">
              <i class="glyphicon glyphicon-film"></i>
              回忆
            </a>
          </li>
          <li>
            <a href="http://www.douban.com/people/yfwz100/doulists/all">
              <i class="glyphicon glyphicon-tag"></i>
              收藏
            </a>
          </li>
          <li>
            <a href="/contact">
              <i class="glyphicon glyphicon-comment"></i>
              联系
            </a>
          </li>
          <li>
            <a href="/about">
              <i class="glyphicon glyphicon-user"></i>
              关于
            </a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="http://weibo.com/yfwz100">@yfwz100</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="home animated fadeIn">
    <div id="carousel-header" class="start main site carousel slide"
         data-interval="false">

      <div class="postcode">
        <a class="item" data-target="#carousel-header" data-slide-to="0">5</a>
        <a class="item" data-target="#carousel-header" data-slide-to="1">2</a>
        <a class="item" data-target="#carousel-header" data-slide-to="2">7</a>
        <a class="item" data-target="#carousel-header" data-slide-to="3">3</a>
        <a class="item" data-target="#carousel-header" data-slide-to="4">0</a>
        <a class="item" data-target="#carousel-header" data-slide-to="5">0</a>
      </div>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <?php foreach($headerPics as $k=>$pic): ?>
        <div class="item <?php echo $k==0?'active':''; ?>">
          <img src="<?php echo $pic; ?>" />
        </div>
        <?php endforeach; ?>
      </div>
    </div>

    <div class="footer">
      『大爱这个美好的世界！』
    </div>
  </div>
</body>

</html>
