<!doctype html>
<html class="site background">

<head>
  <meta charset="utf-8" />
  <title>管理 - 故事 | Stori</title>
  <meta name="keywords" content="Stori, 小故事" />
  <meta name="description" content="一个讲故事的小网站。" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/animate.css/3.5.0/animate.min.css" />
<!--  <link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" />-->
  <link rel="stylesheet" type="text/css" href="css/v3-admin.css" />
<!--  <link rel="stylesheet" type="text/css" href="css/header" />-->
  <script type="application/javascript" src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
<!--  <script type="application/javascript" src="js/home.js"></script>-->
  <script src="//cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body class="jumbotron">
  <main class="v3">
    <div class="container">
      <div class="page-header">
        <h1>管理 <small>The road to the secret place.</small></h1>
      </div>
      <div class="row">
        <div class="col-md-8">
          <form class="form" method="post">
            <div class="input-group input-group-lg">
              <input class="form-control" type="password" name="password" value="" placeholder="密码" />
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">登录</button>
              </span>
            </div>
          </form>
        </div>
      </div>
      <hr/>
      <p><a href="/">返回首页</a></p>
    </div>
  </main>
</body>
</html>
